# doc: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
max_width = 180
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
fn_params_layout = "Vertical"
match_block_trailing_comma = true
use_field_init_shorthand = true

## nightly version only
#format_strings = true
#force_multiline_blocks = true
#overflow_delimited_expr = true
#wrap_comments = true
#blank_lines_upper_bound = 1
#blank_lines_lower_bound = 0